name: Staging Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.ENV_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm install

      - name: Build code, then publish to Vercel
        run: >
          vercel
          --token ${{ secrets.VERCEL_TOKEN }}
          -n ${{ vars.VERCEL_PROJECT }}
          --yes
          --prod
          --env NEXT_PUBLIC_CMS_URL=${{ vars.CMS_BASE_URL }}
          --env CMS_API_KEY=${{ secrets.CMS_API_KEY }}
          --build-env NEXT_PUBLIC_CMS_URL=${{ vars.CMS_BASE_URL }}
          --build-env CMS_API_KEY=${{ secrets.CMS_API_KEY }}

      - name: Success
        run: echo "🛠️ Deploy successful 🛠️"
